import 'package:google_fonts/google_fonts.dart';

///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Res {
  Res._();

  static String appFontFamily = GoogleFonts.cairo().fontFamily ?? '';

  //========================== Api Endpoints  ===============================
  static const apiLogin = 'login';

  //========================== Animation Assets  ===============================
  static const String animApiLoading = 'assets/anim/api_loading.json';
  static const String animApiEmpty = 'assets/anim/api_empty.json';
  static const String animApiError = 'assets/anim/api_error.json';
  static const String animDelivery = 'assets/anim/delivery.json';
  static const String animEmptyCart = 'assets/anim/empty_cart.json';
  static const String animSuccess = 'assets/anim/success.json';
  static const String animDisconnect = 'assets/anim/disconnect.json';

  //========================== Icons Assets  ===============================
  static const String iconName = 'assets/icons/name.svg';
  static const String iconEmail = 'assets/icons/email.svg';
  static const String iconPhone = 'assets/icons/phone.svg';
  static const String iconPassword = 'assets/icons/password.svg';
  static const String iconSuccess = 'assets/icons/success.svg';
  static const String iconLocation = 'assets/icons/location.svg';
  static const String iconPhoneVerified = 'assets/icons/phone_verified.svg';
  static const String iconForgetPassword = 'assets/icons/forget_password.svg';
  static const String iconParking = 'assets/icons/parking.svg';
  static const String iconValet = 'assets/icons/valet.svg';
  static const String iconServices = 'assets/icons/services.svg';
  static const String iconBooking = 'assets/icons/booking.svg';
  static const String iconMenu = 'assets/icons/menu.svg';
  static const String iconNewPassword = 'assets/icons/new_password.svg';
  static const String iconScan = 'assets/icons/scan.svg';

  //========================== Images Assets  ===============================

  static const splashImage = "assets/images/splash_bg.jpg";

  static const facebookImage = "assets/images/social/facebook.png";
  static const instagramImage = "assets/images/social/instagram.png";
  static const twitterImage = "assets/images/social/twitter.png";

  static const logoWhiteImage = "assets/images/launcher/logo_white.png";
  static const logoImage = "assets/images/launcher/logo.png";

  static const notFoundImage = "assets/images/not_found.jpg";
}
