import 'package:google_fonts/google_fonts.dart';

///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Res {
  Res._();

  static String appFontFamily = GoogleFonts.cairo().fontFamily ?? '';

  //========================== Api Endpoints  ===============================
  static const apiLogin = 'auth/login';
  static const apiLogout = 'auth/logout';
  static const apiRegister = 'auth/register';
  static const apiProfile = 'auth/profile';
  static const apiUploadFile = 'storage/file';
  static const apiUpdateProfile = 'auth/profile';
  static const apiCreateContact = 'customer/contact';
  static const apiAllContact = 'customer/contacts';
  static const apiDeleteUser = 'customer/contact';
  static const apiCarColors = 'constants/car-colors-list';
  static const apiCarTypes = 'constants/car-types-list';
  static const apiCar = 'customer/car';
  static const apiAllCars = 'customer/cars';
  static const apiAllAdvertisements = 'customer/advertisements';
  static const apiGetBalance = 'customer/current-balance';
  static const apiGetPaymentOptions = 'constants/charge-price-list';
  static const apiChargeBalance = 'customer/charge-balance';

  //========================== Animation Assets  ===============================
  static const String animApiLoading = 'assets/anim/api_loading.json';
  static const String animApiEmpty = 'assets/anim/api_empty.json';
  static const String animApiError = 'assets/anim/api_error.json';
  static const String animDelivery = 'assets/anim/delivery.json';
  static const String animEmptyCart = 'assets/anim/empty_cart.json';
  static const String animSuccess = 'assets/anim/success.json';
  static const String animDisconnect = 'assets/anim/disconnect.json';

  //========================== Icons Assets  ===============================
  static const String iconName = 'assets/icons/name.svg';
  static const String iconEmail = 'assets/icons/email.svg';
  static const String iconPhone = 'assets/icons/phone.svg';
  static const String iconPassword = 'assets/icons/password.svg';
  static const String iconSuccess = 'assets/icons/success.svg';
  static const String iconError = 'assets/icons/error.svg';
  static const String iconLocation = 'assets/icons/location.svg';
  static const String iconPhoneVerified = 'assets/icons/phone_verified.svg';
  static const String iconForgetPassword = 'assets/icons/forget_password.svg';
  static const String iconParking = 'assets/icons/parking.svg';
  static const String iconValet = 'assets/icons/valet.svg';
  static const String iconServices = 'assets/icons/services.svg';
  static const String iconBooking = 'assets/icons/booking.svg';
  static const String iconMenu = 'assets/icons/menu.svg';
  static const String iconNewPassword = 'assets/icons/new_password.svg';
  static const String iconScan = 'assets/icons/scan.svg';
  static const String iconMale = 'assets/icons/male.svg';
  static const String iconFemale = 'assets/icons/female.svg';
  static const String iconEmptyUsers = 'assets/icons/empty_users.svg';
  static const String iconEmptyCars = 'assets/icons/empty_cars.svg';
  static const String iconEmptyServices = 'assets/icons/empty_services.svg';

  //========================== Images Assets  ===============================

  static const facebookImage = "assets/images/social/facebook.png";
  static const instagramImage = "assets/images/social/instagram.png";
  static const twitterImage = "assets/images/social/twitter.png";

  static const logoWhiteImage = "assets/images/launcher/logo_white.png";
  static const logoImage = "assets/images/launcher/logo.png";

  static const notFoundImage = "assets/images/not_found.png";
  static const personImage = "assets/images/person.png";
}
