name: vpm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.4.0
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  fcm_config: ^3.5.3
  shimmer: ^3.0.0
  #  dart run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.2
  intl: ^0.18.0
  lottie: ^2.7.0
  connectivity_plus: ^5.0.2
  pretty_dio_logger: ^1.3.1
  oktoast: ^3.4.0
  package_info_plus: ^5.0.1
  syncfusion_flutter_datepicker: ^24.1.41
  google_fonts: ^6.1.0
  flutter_onboarding_slider: ^1.0.11
  flutter_native_splash: ^2.3.9
  vibration: ^1.8.4
  intl_phone_field: ^3.2.0
  auto_animated: ^3.2.0
  pin_code_fields: ^8.0.1
  timer_count_down: ^2.2.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter: ^2.5.1
  toggle_switch: ^2.1.0
  flutter_inappwebview: ^6.0.0
  qr_flutter: ^4.1.0
  #  check flutter_native_splash.yaml in root directory to change configurations
  #  dart run flutter_native_splash:create ==> to apply
  #  dart run flutter_native_splash:remove ==> to remove


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: assets/images/launcher/logo.png
  image_path_android: assets/images/launcher/logo.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/launcher/
    - assets/images/intro/
    - assets/icons/
    - assets/anim/
